---
# 定义组变量


#################### 进程守护  ################################################
# 配置supervisor
supervisor:
  port: 9001

#################### 数据库部分  ###############################################
# pg的主库
pg_primary:
  # 创建一个新的用户pgadmin，有dba权限, 指定数据存放的目录
  data_dir: /opt/data/pgsql/data
  db_user: pgadmin
  pgpass: 123456
  db_host: 192.168.0.241
  pgport: 5432
  # MB
  memory_limit: 4096

# 配置初始化数据库(pg-load)的配置
pg_load:
  db_user: pgadmin
  db_name: dxp
  db_host: 192.168.0.241
  pgpass: 123456
  pgport: 5432

# 配置Oracle11gR2
oracle11gr2:
  app_dir: /u01
  data_dir: /u02
  sid: orcl
  hostname: "ora01.bd.sabo.com"
  # MB, 内存要小于/dev/shm分配的内存
  memory_limit: 6144
  password: Oracle_001
  notification_email: canbin.zhang@qq.com

# oracle19c
oracle19c:
  app_dir: /u01
  data_dir: /u02
  sid: orcl
  hostname: "ora01.bd.sabo.com"
  # mode: Data_Warehouse.dbc 或者 General_Purpose.dbc
  mode: "General_Purpose.dbc"
  # MB, 内存要小于/dev/shm分配的内存
  memory_limit: 6144
  password: Oracle_002
  notification_email: canbin.zhang@qq.com

# 配置primary mysql
mysql_primary:
  db_host: 192.168.0.241
  db_user: myadmin
  dbpass: Windows_8
  data_dir: /opt/data/mysql
  # G
  memory_limit: 4

# ldap
ldap:
  passwd: "123456"
  domain: "dc=sabo,dc=com"
  short_domain: "sabo"
  organization: "sabo.com"
  # mirror mode, 至少需要两台机器
  server_01: 192.168.0.34
  server_02: 192.168.0.35

# Greenplum
gp:
  password: 123456
  dbname: gpdb
  master_data_directory: /opt/data/master
  primary_data_directory:
    # 一台机器上布置几个segment就设置几个路径, 比如下面的就会安装两个segment
    - /opt/data/primary
    - /opt/data/primary
  mdw:
    hostname: mdw
    ip: 192.168.0.34
  sdws:
    - hostname: sdw1
      ip: 192.168.0.35
    - hostname: sdw2
      ip: 192.168.0.37

#################### ETL部分  ###############################################
# Nifi
nifi:
  port: 8022
  zk: "192.168.0.181:2181"
  dir_flowfile: "./flowfile_repository"
  # content的IO最高
  dir_content: "./content_repository"
  dir_provenance: "./provenance_repository"


#################### 监控部分  ###############################################
# 配置 Prometheus, 单节点或者多节点之后nginx代理的地址
prometheus:
  host: 127.0.0.1
  port: 9090

jobs:
  - name: job1
    targets:
      - host: 127.0.0.1
        port: 9090
      - host: 127.0.0.1
        port: 9100
    labels:
      - key: "env"
        value: "dev"

# 配置node_exporter端口, 默认是9100
node_exporter:
  port: 9100

# 配置grafana的端口
grafana:
  port: 3000
  host: 127.0.0.1

# 配置告警的服务
alertmanager:
  host: 127.0.0.1
  port: 9093

#################### 调度部分  ###############################################
# 注意要确保role执行的次序
# zookeeper-standalone dolphinscheduler2.0.0-pg
# dolphinscheduler2.0.0-api dolphinscheduler2.0.0-alert dolphinscheduler2.0.0-master dolphinscheduler2.0.0-worker

ds:
  # hostnames: ips="ds1,ds2,ds3,ds4,ds5", Example for IPs: ips="192.168.8.1,192.168.8.2,192.168.8.3,192.168.8.4,192.168.8.5"
  ips: "127.0.0.1"
  # hostnames: masters="ds1,ds2", Example for IPs: masters="192.168.8.1,192.168.8.2"
  masters: "127.0.0.1"
  # hostnames: workers="ds1:default,ds2:default,ds3:default", Example for IPs: workers="192.168.8.1:default,192.168.8.2:default,192.168.8.3:default"
  workers: "127.0.0.1:default"
  # hostname: alertServer="ds3", Example for IP: alertServer="192.168.8.3"
  alert: "127.0.0.1"
  # hostname: apiServers="ds1", Example for IP: apiServers="192.168.8.1"
  api: "127.0.0.1"
  api_port: "12345"
  # 192.168.8.1:2181,192.168.8.2:2181,192.168.8.3:2181
  zk: "127.0.0.1:2181"
  db_user: "dolphinscheduler"
  db_pass: "dolphinscheduler"
  dbname: "dolphinscheduler"
