SELECT '${systemCode}' AS SYSID,
 '${dbid}' AS DBID,
 'mysql5.7' AS dbtype,
 l.TABLE_SCHEMA AS SCHNAME,
 l.TABLE_TYPE AS tabtype,
 l.TABLE_COLLATION AS tabcharset,
 l.ENGINE AS tabengine,
 l.TABLE_NAME AS TABNAME,
 l.TABLE_COMMENT AS TABCHNAME, IFNULL(r.TABLESPACE_NAME, '') AS TABSPACENAME,
 l.TABLE_ROWS AS ROWCOUNT,
 l.DATA_LENGTH AS TSIZE,
 l.DATA_FREE AS FREESIZE,
 l.CREATE_TIME AS CRTDATE,
 l.UPDATE_TIME AS MODIFYDATE, IFNULL(r.partitionsinfo, '') AS partitionsinfo, IFNULL(l.indexesinfo, '') AS indexesinfo,
 '' AS ROWFORMAT,
 '' AS FILEFORMAT,
 '' AS FILELOCATION,
 '${metaDate}' AS VERSION
FROM
(
SELECT
t0.TABLE_SCHEMA AS TABLE_SCHEMA,
t0.TABLE_NAME AS TABLE_NAME, CASE WHEN t0.TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE 'VIEW' END AS TABLE_TYPE, IFNULL(t0.ENGINE, '') AS ENGINE, IFNULL(t0.TABLE_ROWS, 0) AS TABLE_ROWS, IFNULL(t0.DATA_LENGTH, 0) AS DATA_LENGTH, IFNULL(t0.DATA_FREE, 0) AS DATA_FREE, IFNULL(DATE_FORMAT(t0.CREATE_TIME, '%Y%m%d%h%m%s'), '') AS CREATE_TIME, IFNULL(DATE_FORMAT(t0.UPDATE_TIME, '%Y%m%d%h%m%s'), IFNULL(DATE_FORMAT(t0.CREATE_TIME, '%Y%m%d%h%m%s'), '')) AS UPDATE_TIME, IFNULL(t0.TABLE_COLLATION, '') AS TABLE_COLLATION,
t0.TABLE_COMMENT AS TABLE_COMMENT,
t1.indexesinfo AS indexesinfo
FROM information_schema.TABLES t0
LEFT JOIN

(
SELECT TABLE_SCHEMA, TABLE_NAME, GROUP_CONCAT(indexesinfo) AS indexesinfo
FROM (
SELECT TABLE_SCHEMA, TABLE_NAME, CONCAT(INDEX_NAME, '->', COLUMN_NAME, ':', INDEX_TYPE) AS indexesinfo
FROM information_schema.STATISTICS
) AS t
GROUP BY TABLE_SCHEMA, TABLE_NAME) AS t1 ON t0.TABLE_SCHEMA = t1.TABLE_SCHEMA AND t0.TABLE_NAME = t1.TABLE_NAME
) l
LEFT JOIN

(
SELECT TABLE_SCHEMA,TABLE_NAME, GROUP_CONCAT(partitionsinfo) AS partitionsinfo, MAX(TABLESPACE_NAME) TABLESPACE_NAME
FROM (
SELECT TABLE_SCHEMA,TABLE_NAME, CONCAT_WS(',', PARTITION_NAME,PARTITION_METHOD,PARTITION_EXPRESSION,PARTITION_DESCRIPTION) AS partitionsinfo, IFNULL(TABLESPACE_NAME, '') AS TABLESPACE_NAME
FROM information_schema.PARTITIONS
) AS t
GROUP BY TABLE_SCHEMA,TABLE_NAME
) r ON l.TABLE_SCHEMA = r.TABLE_SCHEMA AND l.TABLE_NAME = r.TABLE_NAME
