---

- name: Prepare java path -> /usr/local/java
  file:
    path: "/usr/local/java"
    state: directory

- name: Extract amazon-corretto-8.362.08.1-linux-x64.tar.gz to /usr/local/java/amazon-corretto-8.362.08.1-linux-x64
  unarchive:
    src: "3rd-repo/jdk/amazon-corretto-8.362.08.1-linux-x64.tar.gz"
    dest: "/usr/local/java"
    remote_src: no

- name: create path for java default link
  file:
    path: "/usr/java"
    state: directory

- name: Create default jave symbol link
  file:
    src: "/usr/local/java/amazon-corretto-8.362.08.1-linux-x64"
    dest: "/usr/java/default"
    state: link

- name: Config JAVA_HOME path
  template:
    src:  "{{ item }}.j2"
    dest: "/etc/profile.d/{{ item }}"
  with_items:
    - aws-jdk8.sh
