---

- name: Install postgresql server.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - expect
    - tmpwatch
    - postgresql11-server
    - postgresql11-contrib

- name: Create pg data directory if not exist
  file:
    path: "{{ pg_primary.data_dir }}"
    state: directory
    owner: postgres
    group: postgres

- name: config systemd of pg and change data dir of pg.
  template:
    src:  "postgresql-11.service.j2"
    dest: "/usr/lib/systemd/system/postgresql-11.service"

- name: postgres initdb.
  command: postgresql-11-setup initdb
  args:
    creates: "{{ pg_primary.data_dir }}/log"

- name: stat of pg_archive
  stat: path=/opt/data/pgsql/pg_archive
  register: pg_archive_stat

- name: Config postgresql
  template:
    src:  "{{ item }}.j2"
    dest: "{{ pg_primary.data_dir }}/{{ item }}"
  with_items:
    - postgresql.conf
    - pg_hba.conf
  when: not pg_archive_stat.stat.exists

- name: Start pg && enable postgresql-server auto-start on restart
  systemd:
    name: postgresql-11
    state: started
    enabled: True

- name: create replica user repuser
  shell: |
    set timeout 300
    spawn createuser -U postgres repuser -P -c 5 --replication

    expect "Enter password for new role:"
    send "123456\n"

    expect "Enter it again:"
    send "123456\n"

    expect "\r\n"
    expect ""
    expect ""
    expect eof
    
    exit 0
  args:
    executable: /usr/bin/expect
    chdir: /tmp
    creates: /opt/data/pgsql/pg_archive
  become: yes
  become_user: postgres
  
- name: Create postgresql user({{ pg_primary.db_user }}) && set password({{ pg_primary.pgpass }}).
  shell: |
    set timeout 300
    spawn createuser --interactive --pwprompt {{ pg_primary.db_user }}

    expect "Enter password for new role:"
    send "{{ pg_primary.pgpass }}\n"

    expect "Enter it again:"
    send "{{ pg_primary.pgpass }}\n"

    expect "Shall the new role be a superuser? (y/n)"
    send "y\n"

    expect "Shall the new role be allowed to create databases? (y/n)"
    send "y\n"

    expect "Shall the new role be allowed to create more new roles? (y/n)"
    send "y\n"

    expect "\r\n"
    expect ""
    expect ""
    expect eof
    
    exit 0
  args:
    executable: /usr/bin/expect
    chdir: /tmp
    creates: /opt/data/pgsql/pg_archive
  become: yes
  become_user: postgres

- name: Create archive directory
  file:
    path: /opt/data/pgsql/pg_archive
    state: directory
    owner: postgres
    group: postgres

- name: reconfig this pg and make it be the primary pg.
  template:
    src:  "{{ item }}-primary.conf.j2"
    dest: "{{ pg_primary.data_dir }}/{{ item }}.conf"
  with_items:
    - postgresql
    - pg_hba

- name: restart primary pg
  systemd:
    name: postgresql-11
    state: restarted

- name: config daily crontab job config
  template:
    src:  "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
  with_items:
    - daily.cron

- name: config daily crontab job
  command: crontab /tmp/daily.cron
  when: not pg_archive_stat.stat.exists
