---

- name: Create /opt/app/node_exporter if it does not exist
  file:
    path: /opt/app/node_exporter
    state: directory

- name: Create /opt/log/node_exporter if it does not exist
  file:
    path: /opt/log/node_exporter
    state: directory

- name: Extract node_exporter-1.0.1.linux-amd64.tar.gz into /opt/app/prometheus
  unarchive:
    src: "3rd-repo/node_exporter/node_exporter-1.0.1.linux-amd64.tar.gz"
    dest: /opt/app/node_exporter
    remote_src: no

- name: Create a node_exporter symbolic link
  file:
    src: /opt/app/node_exporter/node_exporter-1.0.1.linux-amd64
    dest: /opt/app/node_exporter/current
    state: link

- name: Config suervisor to start node_exporter
  template:
    src: node_exporter.ini.j2
    dest: /etc/supervisord.d/node_exporter.ini

- name: Start node_exporter
  command: supervisorctl update node_exporter

# 保证运行的程序是最新的
- name: Restart node_exporter
  command: supervisorctl restart node_exporter
