---

# Passwordless SSH
- name: Enabling Passwordless SSH
  shell: |
    # ssh Passwordless 1-n
    while read -r line
    do
      SSHPASS="{{ gp.password }}" sshpass -e ssh-copy-id -o "StrictHostKeyChecking=no" "${line}"
    done < /home/gpadmin/hostfile_exkeys
    # build n-n Passwordless
    source /usr/local/greenplum-db/greenplum_path.sh
    gpssh-exkeys -f /home/gpadmin/hostfile_exkeys
    # end
    exit 0
  args:
    executable: /bin/bash
    chdir: /tmp
  become: yes
  become_user: gpadmin

- name: Config hostfile_gpinitsys & gpinitsystem_config
  template:
    src:  "{{ item }}.j2"
    dest: "/home/gpadmin/{{ item }}"
  with_items:
    - hostfile_gpinitsys
    - gpinitsystem_config
    - gp_init.sh
  become: yes
  become_user: gpadmin

- name: Init Greenplum
  shell: bash /home/gpadmin/gp_init.sh
  become: yes
  become_user: gpadmin

- name: Add more master env
  shell: echo 'export MASTER_DATA_DIRECTORY={{ gp.master_data_directory }}/gpseg-1' >> /home/gpadmin/.bashrc